### PR TITLE
chrono::Date<chrono::offset::Utc> does not support deserialization

### PR DESCRIPTION
**Pull request by pcrumley**
Hi typify team!

This is my first PR to the typify repo and it's to fix a small bug in the typify library, that is that the `Date` option in the json schema doesn't compile because the thing it converts it to `chrono::Date<chrono::offset::Utc>` does not support serde::Deserialize. In addition this type is deprecated and it is suggested to use NaiveDate instead.

Technically this is a breaking change to the library but I'm kind of skeptical it ever worked because it is not compilable & it is not tested in the code as far as I can tell with a simple grep.

Let me know if there is sometime more i need to do to get this PR merged.

Thanks,

### CODE REVIEW

**Comment by ahl** [comment]
Thanks for this. Could you please add a test here: https://github.com/oxidecomputer/typify/tree/main/typify/tests/schemas

These files are all compiled into rust and then ... compiled as Rust.

**Comment by pcrumley** [comment]
@ahl I added test coverage. Thanks for pointing me in correct direction

**Comment by ahl** [comment]
Excellent. Would that have failed to compile on some "couldn't derive `Serialize` because K is not `Serialize`" or something?

**Comment by pcrumley** [comment]
ack! i thought it was so simple i didnt need to run it locally. Here i fixed the tests locally for me now. As the code stands in main branch if you replaces this with `chrono::Date<chrono::offset::Utc>` you would get the following error.

```

error[E0277]: the trait bound `Date<Utc>: Deserialize<'_>` is not satisfied
  --> tests/schemas/maps.rs:61:28
   |
61 | pub struct MapWithDateKeys(pub std::collections::HashMap<chrono::Date<chrono::offset::Utc>, Value>);
   |                            ^^^ the trait `Deserialize<'_>` is not implemented for `Date<Utc>`
   |
   = help: the following other types implement trait `Deserialize<'de>`:
   ```

**Review by ahl — APPROVED** [review]
much obliged! thanks for the PR!

**Pull request merged**
