### PR TITLE
Fix issue #533

### PR DESCRIPTION
**Pull request by SRetip**
Close https://github.com/oxidecomputer/typify/issues/533
first case:
image
seckond case:
image
third case:
image
fourth case:
image

### CODE REVIEW

**Review by ahl — CHANGES_REQUESTED** [review]
Thank you for this. I don't think we want to special-case a `$ref` and object-related data. Rather, this should work for a `$ref` with anything else. In addition, extensive merge logic already exists. If you'd like further guidance, please let me know; otherwise I'll fix this as I have time.

**Comment by ahl** [comment]
I think the essence of this is going to be that we match a schema in which $ref is Some and other stuff might not be None, then do something like:

```rust
    let schema_without_ref = SchemaObject { reference: None, .. schema.clone() }.into();
    let schema_only_ref = SchemaObject { reference: reference.clone(), .. Default::default() };
    let new_schema = merge_all([schema_without_ref, schema_only_ref], defs);
    self.convert(new_schema ..)
```

Also, we'll want a test. Probably in merged-schemas.json.

**Comment by ahl** [comment]
Please add a test.

**Comment by SRetip** [comment]
I hope that's the test you mean the right one.

**Review by ahl — APPROVED** [review]
looks good

**Pull request merged**
